# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExtAppealImageAlbumOneSlotSetElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExtAppealImageAlbumOneSlotSetElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExtAppealImageAlbumOneSlotSetElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExtAppealImageAlbumOneSlotSetElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExtAppealImageAlbumOneSlotSetElement
    def AddedDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ExtAppealImageAlbumOneSlotSetElement
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ExtAppealImageAlbumOneSlotSetElement
    def ProductType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def ExtAppealImageAlbumOneSlotSetElementStart(builder):
    builder.StartObject(3)

def Start(builder):
    ExtAppealImageAlbumOneSlotSetElementStart(builder)

def ExtAppealImageAlbumOneSlotSetElementAddAddedDate(builder, addedDate):
    builder.PrependInt64Slot(0, addedDate, 0)

def AddAddedDate(builder, addedDate):
    ExtAppealImageAlbumOneSlotSetElementAddAddedDate(builder, addedDate)

def ExtAppealImageAlbumOneSlotSetElementAddState(builder, state):
    builder.PrependUint8Slot(1, state, 0)

def AddState(builder, state):
    ExtAppealImageAlbumOneSlotSetElementAddState(builder, state)

def ExtAppealImageAlbumOneSlotSetElementAddProductType(builder, productType):
    builder.PrependUint8Slot(2, productType, 0)

def AddProductType(builder, productType):
    ExtAppealImageAlbumOneSlotSetElementAddProductType(builder, productType)

def ExtAppealImageAlbumOneSlotSetElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExtAppealImageAlbumOneSlotSetElementEnd(builder)
