# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExtARHistoryElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExtARHistoryElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExtARHistoryElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExtARHistoryElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExtARHistoryElement
    def TypeHistory(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ExtARHistoryElement
    def FriendId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExtARHistoryElement
    def NpcId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ExtARHistoryElementStart(builder):
    builder.StartObject(3)

def Start(builder):
    ExtARHistoryElementStart(builder)

def ExtARHistoryElementAddTypeHistory(builder, typeHistory):
    builder.PrependUint8Slot(0, typeHistory, 0)

def AddTypeHistory(builder, typeHistory):
    ExtARHistoryElementAddTypeHistory(builder, typeHistory)

def ExtARHistoryElementAddFriendId(builder, friendId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(friendId), 0)

def AddFriendId(builder, friendId):
    ExtARHistoryElementAddFriendId(builder, friendId)

def ExtARHistoryElementAddNpcId(builder, npcId):
    builder.PrependUint32Slot(2, npcId, 0)

def AddNpcId(builder, npcId):
    ExtARHistoryElementAddNpcId(builder, npcId)

def ExtARHistoryElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExtARHistoryElementEnd(builder)
