# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExtCraftLimitOneSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExtCraftLimitOneSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExtCraftLimitOneSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExtCraftLimitOneSlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExtCraftLimitOneSlot
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExtCraftLimitOneSlot
    def RecipeItemId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExtCraftLimitOneSlot
    def CraftCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExtCraftLimitOneSlot
    def LastResetCampaignId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ExtCraftLimitOneSlotStart(builder):
    builder.StartObject(4)

def Start(builder):
    ExtCraftLimitOneSlotStart(builder)

def ExtCraftLimitOneSlotAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    ExtCraftLimitOneSlotAddId(builder, id)

def ExtCraftLimitOneSlotAddRecipeItemId(builder, recipeItemId):
    builder.PrependUint32Slot(1, recipeItemId, 0)

def AddRecipeItemId(builder, recipeItemId):
    ExtCraftLimitOneSlotAddRecipeItemId(builder, recipeItemId)

def ExtCraftLimitOneSlotAddCraftCount(builder, craftCount):
    builder.PrependUint32Slot(2, craftCount, 0)

def AddCraftCount(builder, craftCount):
    ExtCraftLimitOneSlotAddCraftCount(builder, craftCount)

def ExtCraftLimitOneSlotAddLastResetCampaignId(builder, lastResetCampaignId):
    builder.PrependUint32Slot(3, lastResetCampaignId, 0)

def AddLastResetCampaignId(builder, lastResetCampaignId):
    ExtCraftLimitOneSlotAddLastResetCampaignId(builder, lastResetCampaignId)

def ExtCraftLimitOneSlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExtCraftLimitOneSlotEnd(builder)
