# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExtDiaryEntryOneSlotSetElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExtDiaryEntryOneSlotSetElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExtDiaryEntryOneSlotSetElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExtDiaryEntryOneSlotSetElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExtDiaryEntryOneSlotSetElement
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ExtDiaryEntryOneSlotSetElement
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ExtDiaryEntryOneSlotSetElement
    def ValueAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ExtDiaryEntryOneSlotSetElement
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExtDiaryEntryOneSlotSetElement
    def ValueIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ExtDiaryEntryOneSlotSetElementStart(builder):
    builder.StartObject(2)

def Start(builder):
    ExtDiaryEntryOneSlotSetElementStart(builder)

def ExtDiaryEntryOneSlotSetElementAddTimestamp(builder, timestamp):
    builder.PrependInt64Slot(0, timestamp, 0)

def AddTimestamp(builder, timestamp):
    ExtDiaryEntryOneSlotSetElementAddTimestamp(builder, timestamp)

def ExtDiaryEntryOneSlotSetElementAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    ExtDiaryEntryOneSlotSetElementAddValue(builder, value)

def ExtDiaryEntryOneSlotSetElementStartValueVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartValueVector(builder, numElems):
    return ExtDiaryEntryOneSlotSetElementStartValueVector(builder, numElems)

def ExtDiaryEntryOneSlotSetElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExtDiaryEntryOneSlotSetElementEnd(builder)
