# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExtFriendGiftSendHistory(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExtFriendGiftSendHistory()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExtFriendGiftSendHistory(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExtFriendGiftSendHistory
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExtFriendGiftSendHistory
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExtFriendGiftSendHistory
    def NewDayUnixTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ExtFriendGiftSendHistory
    def Elements(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Acpcc.ExtFriendGiftSendHistoryElement import ExtFriendGiftSendHistoryElement
            obj = ExtFriendGiftSendHistoryElement()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExtFriendGiftSendHistory
    def ElementsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExtFriendGiftSendHistory
    def ElementsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def ExtFriendGiftSendHistoryStart(builder):
    builder.StartObject(3)

def Start(builder):
    ExtFriendGiftSendHistoryStart(builder)

def ExtFriendGiftSendHistoryAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    ExtFriendGiftSendHistoryAddId(builder, id)

def ExtFriendGiftSendHistoryAddNewDayUnixTime(builder, newDayUnixTime):
    builder.PrependInt64Slot(1, newDayUnixTime, 0)

def AddNewDayUnixTime(builder, newDayUnixTime):
    ExtFriendGiftSendHistoryAddNewDayUnixTime(builder, newDayUnixTime)

def ExtFriendGiftSendHistoryAddElements(builder, elements):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(elements), 0)

def AddElements(builder, elements):
    ExtFriendGiftSendHistoryAddElements(builder, elements)

def ExtFriendGiftSendHistoryStartElementsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartElementsVector(builder, numElems):
    return ExtFriendGiftSendHistoryStartElementsVector(builder, numElems)

def ExtFriendGiftSendHistoryEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExtFriendGiftSendHistoryEnd(builder)
