# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExtFriendGiftSendHistoryElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExtFriendGiftSendHistoryElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExtFriendGiftSendHistoryElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExtFriendGiftSendHistoryElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExtFriendGiftSendHistoryElement
    def PlayerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ExtFriendGiftSendHistoryElementStart(builder):
    builder.StartObject(1)

def Start(builder):
    ExtFriendGiftSendHistoryElementStart(builder)

def ExtFriendGiftSendHistoryElementAddPlayerId(builder, playerId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(playerId), 0)

def AddPlayerId(builder, playerId):
    ExtFriendGiftSendHistoryElementAddPlayerId(builder, playerId)

def ExtFriendGiftSendHistoryElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExtFriendGiftSendHistoryElementEnd(builder)
