# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserCraftCampaignRecipeCheck(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserCraftCampaignRecipeCheck()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserCraftCampaignRecipeCheck(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserCraftCampaignRecipeCheck
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserCraftCampaignRecipeCheck
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserCraftCampaignRecipeCheck
    def RecordId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserCraftCampaignRecipeCheck
    def CampaignId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserCraftCampaignRecipeCheck
    def RecordType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def UserCraftCampaignRecipeCheckStart(builder):
    builder.StartObject(4)

def Start(builder):
    UserCraftCampaignRecipeCheckStart(builder)

def UserCraftCampaignRecipeCheckAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserCraftCampaignRecipeCheckAddId(builder, id)

def UserCraftCampaignRecipeCheckAddRecordId(builder, recordId):
    builder.PrependUint32Slot(1, recordId, 0)

def AddRecordId(builder, recordId):
    UserCraftCampaignRecipeCheckAddRecordId(builder, recordId)

def UserCraftCampaignRecipeCheckAddCampaignId(builder, campaignId):
    builder.PrependUint32Slot(2, campaignId, 0)

def AddCampaignId(builder, campaignId):
    UserCraftCampaignRecipeCheckAddCampaignId(builder, campaignId)

def UserCraftCampaignRecipeCheckAddRecordType(builder, recordType):
    builder.PrependInt32Slot(3, recordType, 0)

def AddRecordType(builder, recordType):
    UserCraftCampaignRecipeCheckAddRecordType(builder, recordType)

def UserCraftCampaignRecipeCheckEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserCraftCampaignRecipeCheckEnd(builder)
