# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserLoan(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserLoan()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserLoan(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserLoan
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserLoan
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserLoan
    def LoanCarIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserLoan
    def LoanProgress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserLoan
    def LoanMoney(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def UserLoanStart(builder):
    builder.StartObject(4)

def Start(builder):
    UserLoanStart(builder)

def UserLoanAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserLoanAddId(builder, id)

def UserLoanAddLoanCarIndex(builder, loanCarIndex):
    builder.PrependInt32Slot(1, loanCarIndex, 0)

def AddLoanCarIndex(builder, loanCarIndex):
    UserLoanAddLoanCarIndex(builder, loanCarIndex)

def UserLoanAddLoanProgress(builder, loanProgress):
    builder.PrependInt32Slot(2, loanProgress, 0)

def AddLoanProgress(builder, loanProgress):
    UserLoanAddLoanProgress(builder, loanProgress)

def UserLoanAddLoanMoney(builder, loanMoney):
    builder.PrependInt32Slot(3, loanMoney, 0)

def AddLoanMoney(builder, loanMoney):
    UserLoanAddLoanMoney(builder, loanMoney)

def UserLoanEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserLoanEnd(builder)
