# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserEventLogSlotElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserEventLogSlotElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserEventLogSlotElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserEventLogSlotElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserEventLogSlotElement
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserEventLogSlotElement
    def IsFixed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserEventLogSlotElement
    def CampaignId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserEventLogSlotElement
    def TotalPoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserEventLogSlotElement
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserEventLogSlotElement
    def EventNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserEventLogSlotElement
    def RewardItemId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserEventLogSlotElement
    def LabelList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # UserEventLogSlotElement
    def LabelListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserEventLogSlotElement
    def LabelListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # UserEventLogSlotElement
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def UserEventLogSlotElementStart(builder):
    builder.StartObject(9)

def Start(builder):
    UserEventLogSlotElementStart(builder)

def UserEventLogSlotElementAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserEventLogSlotElementAddId(builder, id)

def UserEventLogSlotElementAddIsFixed(builder, isFixed):
    builder.PrependBoolSlot(1, isFixed, 0)

def AddIsFixed(builder, isFixed):
    UserEventLogSlotElementAddIsFixed(builder, isFixed)

def UserEventLogSlotElementAddCampaignId(builder, campaignId):
    builder.PrependUint32Slot(2, campaignId, 0)

def AddCampaignId(builder, campaignId):
    UserEventLogSlotElementAddCampaignId(builder, campaignId)

def UserEventLogSlotElementAddTotalPoint(builder, totalPoint):
    builder.PrependInt64Slot(3, totalPoint, 0)

def AddTotalPoint(builder, totalPoint):
    UserEventLogSlotElementAddTotalPoint(builder, totalPoint)

def UserEventLogSlotElementAddEventType(builder, eventType):
    builder.PrependInt32Slot(4, eventType, 0)

def AddEventType(builder, eventType):
    UserEventLogSlotElementAddEventType(builder, eventType)

def UserEventLogSlotElementAddEventNumber(builder, eventNumber):
    builder.PrependInt32Slot(5, eventNumber, 0)

def AddEventNumber(builder, eventNumber):
    UserEventLogSlotElementAddEventNumber(builder, eventNumber)

def UserEventLogSlotElementAddRewardItemId(builder, rewardItemId):
    builder.PrependUint32Slot(6, rewardItemId, 0)

def AddRewardItemId(builder, rewardItemId):
    UserEventLogSlotElementAddRewardItemId(builder, rewardItemId)

def UserEventLogSlotElementAddLabelList(builder, labelList):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(labelList), 0)

def AddLabelList(builder, labelList):
    UserEventLogSlotElementAddLabelList(builder, labelList)

def UserEventLogSlotElementStartLabelListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLabelListVector(builder, numElems):
    return UserEventLogSlotElementStartLabelListVector(builder, numElems)

def UserEventLogSlotElementAddState(builder, state):
    builder.PrependInt32Slot(8, state, 0)

def AddState(builder, state):
    UserEventLogSlotElementAddState(builder, state)

def UserEventLogSlotElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserEventLogSlotElementEnd(builder)
