# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserMyCampQuestItemNumOneSlotElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserMyCampQuestItemNumOneSlotElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserMyCampQuestItemNumOneSlotElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserMyCampQuestItemNumOneSlotElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserMyCampQuestItemNumOneSlotElement
    def ItemLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserMyCampQuestItemNumOneSlotElement
    def Num(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserMyCampQuestItemNumOneSlotElement
    def ExplicitFlg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserMyCampQuestItemNumOneSlotElement
    def CampaignId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def UserMyCampQuestItemNumOneSlotElementStart(builder):
    builder.StartObject(4)

def Start(builder):
    UserMyCampQuestItemNumOneSlotElementStart(builder)

def UserMyCampQuestItemNumOneSlotElementAddItemLabel(builder, itemLabel):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(itemLabel), 0)

def AddItemLabel(builder, itemLabel):
    UserMyCampQuestItemNumOneSlotElementAddItemLabel(builder, itemLabel)

def UserMyCampQuestItemNumOneSlotElementAddNum(builder, num):
    builder.PrependInt32Slot(1, num, 0)

def AddNum(builder, num):
    UserMyCampQuestItemNumOneSlotElementAddNum(builder, num)

def UserMyCampQuestItemNumOneSlotElementAddExplicitFlg(builder, explicitFlg):
    builder.PrependBoolSlot(2, explicitFlg, 0)

def AddExplicitFlg(builder, explicitFlg):
    UserMyCampQuestItemNumOneSlotElementAddExplicitFlg(builder, explicitFlg)

def UserMyCampQuestItemNumOneSlotElementAddCampaignId(builder, campaignId):
    builder.PrependUint32Slot(3, campaignId, 0)

def AddCampaignId(builder, campaignId):
    UserMyCampQuestItemNumOneSlotElementAddCampaignId(builder, campaignId)

def UserMyCampQuestItemNumOneSlotElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserMyCampQuestItemNumOneSlotElementEnd(builder)
