# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserCottageNpcInfoOneSlotSetElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserCottageNpcInfoOneSlotSetElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserCottageNpcInfoOneSlotSetElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserCottageNpcInfoOneSlotSetElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserCottageNpcInfoOneSlotSetElement
    def CottageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserCottageNpcInfoOneSlotSetElement
    def Floor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserCottageNpcInfoOneSlotSetElement
    def NpcLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCottageNpcInfoOneSlotSetElement
    def ActionLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCottageNpcInfoOneSlotSetElement
    def ActionGroupLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCottageNpcInfoOneSlotSetElement
    def VecRotateX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # UserCottageNpcInfoOneSlotSetElement
    def VecRotateY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # UserCottageNpcInfoOneSlotSetElement
    def VecRotateZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # UserCottageNpcInfoOneSlotSetElement
    def PositionX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # UserCottageNpcInfoOneSlotSetElement
    def PositionY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # UserCottageNpcInfoOneSlotSetElement
    def PositionZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # UserCottageNpcInfoOneSlotSetElement
    def JoinObjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserCottageNpcInfoOneSlotSetElement
    def JoinObjLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCottageNpcInfoOneSlotSetElement
    def JoinObjActFileName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCottageNpcInfoOneSlotSetElement
    def JoinObjUniqueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCottageNpcInfoOneSlotSetElement
    def NpcLocatorKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCottageNpcInfoOneSlotSetElement
    def WearTopsKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCottageNpcInfoOneSlotSetElement
    def WearAcceKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCottageNpcInfoOneSlotSetElement
    def WearCapKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCottageNpcInfoOneSlotSetElement
    def WearDecoKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCottageNpcInfoOneSlotSetElement
    def WearHandItemId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def UserCottageNpcInfoOneSlotSetElementStart(builder):
    builder.StartObject(21)

def Start(builder):
    UserCottageNpcInfoOneSlotSetElementStart(builder)

def UserCottageNpcInfoOneSlotSetElementAddCottageId(builder, cottageId):
    builder.PrependInt32Slot(0, cottageId, 0)

def AddCottageId(builder, cottageId):
    UserCottageNpcInfoOneSlotSetElementAddCottageId(builder, cottageId)

def UserCottageNpcInfoOneSlotSetElementAddFloor(builder, floor):
    builder.PrependInt32Slot(1, floor, 0)

def AddFloor(builder, floor):
    UserCottageNpcInfoOneSlotSetElementAddFloor(builder, floor)

def UserCottageNpcInfoOneSlotSetElementAddNpcLabel(builder, npcLabel):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(npcLabel), 0)

def AddNpcLabel(builder, npcLabel):
    UserCottageNpcInfoOneSlotSetElementAddNpcLabel(builder, npcLabel)

def UserCottageNpcInfoOneSlotSetElementAddActionLabel(builder, actionLabel):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(actionLabel), 0)

def AddActionLabel(builder, actionLabel):
    UserCottageNpcInfoOneSlotSetElementAddActionLabel(builder, actionLabel)

def UserCottageNpcInfoOneSlotSetElementAddActionGroupLabel(builder, actionGroupLabel):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(actionGroupLabel), 0)

def AddActionGroupLabel(builder, actionGroupLabel):
    UserCottageNpcInfoOneSlotSetElementAddActionGroupLabel(builder, actionGroupLabel)

def UserCottageNpcInfoOneSlotSetElementAddVecRotateX(builder, vecRotateX):
    builder.PrependFloat32Slot(5, vecRotateX, 0.0)

def AddVecRotateX(builder, vecRotateX):
    UserCottageNpcInfoOneSlotSetElementAddVecRotateX(builder, vecRotateX)

def UserCottageNpcInfoOneSlotSetElementAddVecRotateY(builder, vecRotateY):
    builder.PrependFloat32Slot(6, vecRotateY, 0.0)

def AddVecRotateY(builder, vecRotateY):
    UserCottageNpcInfoOneSlotSetElementAddVecRotateY(builder, vecRotateY)

def UserCottageNpcInfoOneSlotSetElementAddVecRotateZ(builder, vecRotateZ):
    builder.PrependFloat32Slot(7, vecRotateZ, 0.0)

def AddVecRotateZ(builder, vecRotateZ):
    UserCottageNpcInfoOneSlotSetElementAddVecRotateZ(builder, vecRotateZ)

def UserCottageNpcInfoOneSlotSetElementAddPositionX(builder, positionX):
    builder.PrependFloat32Slot(8, positionX, 0.0)

def AddPositionX(builder, positionX):
    UserCottageNpcInfoOneSlotSetElementAddPositionX(builder, positionX)

def UserCottageNpcInfoOneSlotSetElementAddPositionY(builder, positionY):
    builder.PrependFloat32Slot(9, positionY, 0.0)

def AddPositionY(builder, positionY):
    UserCottageNpcInfoOneSlotSetElementAddPositionY(builder, positionY)

def UserCottageNpcInfoOneSlotSetElementAddPositionZ(builder, positionZ):
    builder.PrependFloat32Slot(10, positionZ, 0.0)

def AddPositionZ(builder, positionZ):
    UserCottageNpcInfoOneSlotSetElementAddPositionZ(builder, positionZ)

def UserCottageNpcInfoOneSlotSetElementAddJoinObjectId(builder, joinObjectId):
    builder.PrependInt32Slot(11, joinObjectId, 0)

def AddJoinObjectId(builder, joinObjectId):
    UserCottageNpcInfoOneSlotSetElementAddJoinObjectId(builder, joinObjectId)

def UserCottageNpcInfoOneSlotSetElementAddJoinObjLabel(builder, joinObjLabel):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(joinObjLabel), 0)

def AddJoinObjLabel(builder, joinObjLabel):
    UserCottageNpcInfoOneSlotSetElementAddJoinObjLabel(builder, joinObjLabel)

def UserCottageNpcInfoOneSlotSetElementAddJoinObjActFileName(builder, joinObjActFileName):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(joinObjActFileName), 0)

def AddJoinObjActFileName(builder, joinObjActFileName):
    UserCottageNpcInfoOneSlotSetElementAddJoinObjActFileName(builder, joinObjActFileName)

def UserCottageNpcInfoOneSlotSetElementAddJoinObjUniqueId(builder, joinObjUniqueId):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(joinObjUniqueId), 0)

def AddJoinObjUniqueId(builder, joinObjUniqueId):
    UserCottageNpcInfoOneSlotSetElementAddJoinObjUniqueId(builder, joinObjUniqueId)

def UserCottageNpcInfoOneSlotSetElementAddNpcLocatorKey(builder, npcLocatorKey):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(npcLocatorKey), 0)

def AddNpcLocatorKey(builder, npcLocatorKey):
    UserCottageNpcInfoOneSlotSetElementAddNpcLocatorKey(builder, npcLocatorKey)

def UserCottageNpcInfoOneSlotSetElementAddWearTopsKey(builder, wearTopsKey):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(wearTopsKey), 0)

def AddWearTopsKey(builder, wearTopsKey):
    UserCottageNpcInfoOneSlotSetElementAddWearTopsKey(builder, wearTopsKey)

def UserCottageNpcInfoOneSlotSetElementAddWearAcceKey(builder, wearAcceKey):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(wearAcceKey), 0)

def AddWearAcceKey(builder, wearAcceKey):
    UserCottageNpcInfoOneSlotSetElementAddWearAcceKey(builder, wearAcceKey)

def UserCottageNpcInfoOneSlotSetElementAddWearCapKey(builder, wearCapKey):
    builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(wearCapKey), 0)

def AddWearCapKey(builder, wearCapKey):
    UserCottageNpcInfoOneSlotSetElementAddWearCapKey(builder, wearCapKey)

def UserCottageNpcInfoOneSlotSetElementAddWearDecoKey(builder, wearDecoKey):
    builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(wearDecoKey), 0)

def AddWearDecoKey(builder, wearDecoKey):
    UserCottageNpcInfoOneSlotSetElementAddWearDecoKey(builder, wearDecoKey)

def UserCottageNpcInfoOneSlotSetElementAddWearHandItemId(builder, wearHandItemId):
    builder.PrependUint32Slot(20, wearHandItemId, 0)

def AddWearHandItemId(builder, wearHandItemId):
    UserCottageNpcInfoOneSlotSetElementAddWearHandItemId(builder, wearHandItemId)

def UserCottageNpcInfoOneSlotSetElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserCottageNpcInfoOneSlotSetElementEnd(builder)
