# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserQuestSozaiElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserQuestSozaiElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserQuestSozaiElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserQuestSozaiElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserQuestSozaiElement
    def TotalPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserQuestSozaiElement
    def QuestItemNumOneSlots(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Acpcc.UserQuestItemNumOneSlotElement import UserQuestItemNumOneSlotElement
            obj = UserQuestItemNumOneSlotElement()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UserQuestSozaiElement
    def QuestItemNumOneSlotsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserQuestSozaiElement
    def QuestItemNumOneSlotsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def UserQuestSozaiElementStart(builder):
    builder.StartObject(2)

def Start(builder):
    UserQuestSozaiElementStart(builder)

def UserQuestSozaiElementAddTotalPrice(builder, totalPrice):
    builder.PrependInt32Slot(0, totalPrice, 0)

def AddTotalPrice(builder, totalPrice):
    UserQuestSozaiElementAddTotalPrice(builder, totalPrice)

def UserQuestSozaiElementAddQuestItemNumOneSlots(builder, questItemNumOneSlots):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(questItemNumOneSlots), 0)

def AddQuestItemNumOneSlots(builder, questItemNumOneSlots):
    UserQuestSozaiElementAddQuestItemNumOneSlots(builder, questItemNumOneSlots)

def UserQuestSozaiElementStartQuestItemNumOneSlotsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartQuestItemNumOneSlotsVector(builder, numElems):
    return UserQuestSozaiElementStartQuestItemNumOneSlotsVector(builder, numElems)

def UserQuestSozaiElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserQuestSozaiElementEnd(builder)
