# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserPaymentRecommendOneSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserPaymentRecommendOneSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserPaymentRecommendOneSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserPaymentRecommendOneSlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserPaymentRecommendOneSlot
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserPaymentRecommendOneSlot
    def RecommendId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserPaymentRecommendOneSlot
    def ShowLastAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def UserPaymentRecommendOneSlotStart(builder):
    builder.StartObject(3)

def Start(builder):
    UserPaymentRecommendOneSlotStart(builder)

def UserPaymentRecommendOneSlotAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserPaymentRecommendOneSlotAddId(builder, id)

def UserPaymentRecommendOneSlotAddRecommendId(builder, recommendId):
    builder.PrependUint32Slot(1, recommendId, 0)

def AddRecommendId(builder, recommendId):
    UserPaymentRecommendOneSlotAddRecommendId(builder, recommendId)

def UserPaymentRecommendOneSlotAddShowLastAt(builder, showLastAt):
    builder.PrependInt64Slot(2, showLastAt, 0)

def AddShowLastAt(builder, showLastAt):
    UserPaymentRecommendOneSlotAddShowLastAt(builder, showLastAt)

def UserPaymentRecommendOneSlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserPaymentRecommendOneSlotEnd(builder)
