# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserCraftCampaignRecipeCheckSet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserCraftCampaignRecipeCheckSet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserCraftCampaignRecipeCheckSet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserCraftCampaignRecipeCheckSet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserCraftCampaignRecipeCheckSet
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserCraftCampaignRecipeCheckSet
    def Elements(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Acpcc.UserCraftCampaignRecipeCheckSetElement import UserCraftCampaignRecipeCheckSetElement
            obj = UserCraftCampaignRecipeCheckSetElement()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UserCraftCampaignRecipeCheckSet
    def ElementsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserCraftCampaignRecipeCheckSet
    def ElementsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def UserCraftCampaignRecipeCheckSetStart(builder):
    builder.StartObject(2)

def Start(builder):
    UserCraftCampaignRecipeCheckSetStart(builder)

def UserCraftCampaignRecipeCheckSetAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserCraftCampaignRecipeCheckSetAddId(builder, id)

def UserCraftCampaignRecipeCheckSetAddElements(builder, elements):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(elements), 0)

def AddElements(builder, elements):
    UserCraftCampaignRecipeCheckSetAddElements(builder, elements)

def UserCraftCampaignRecipeCheckSetStartElementsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartElementsVector(builder, numElems):
    return UserCraftCampaignRecipeCheckSetStartElementsVector(builder, numElems)

def UserCraftCampaignRecipeCheckSetEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserCraftCampaignRecipeCheckSetEnd(builder)
