# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserProfilePublicEquipInfoOneSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserProfilePublicEquipInfoOneSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserProfilePublicEquipInfoOneSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserProfilePublicEquipInfoOneSlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserProfilePublicEquipInfoOneSlot
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserProfilePublicEquipInfoOneSlot
    def ItemLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserProfilePublicEquipInfoOneSlot
    def MyDesignId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UserProfilePublicEquipInfoOneSlotStart(builder):
    builder.StartObject(3)

def Start(builder):
    UserProfilePublicEquipInfoOneSlotStart(builder)

def UserProfilePublicEquipInfoOneSlotAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserProfilePublicEquipInfoOneSlotAddId(builder, id)

def UserProfilePublicEquipInfoOneSlotAddItemLabel(builder, itemLabel):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(itemLabel), 0)

def AddItemLabel(builder, itemLabel):
    UserProfilePublicEquipInfoOneSlotAddItemLabel(builder, itemLabel)

def UserProfilePublicEquipInfoOneSlotAddMyDesignId(builder, myDesignId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(myDesignId), 0)

def AddMyDesignId(builder, myDesignId):
    UserProfilePublicEquipInfoOneSlotAddMyDesignId(builder, myDesignId)

def UserProfilePublicEquipInfoOneSlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserProfilePublicEquipInfoOneSlotEnd(builder)
