# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserGulliverShipDestination(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserGulliverShipDestination()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserGulliverShipDestination(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserGulliverShipDestination
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserGulliverShipDestination
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserGulliverShipDestination
    def DestinationId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserGulliverShipDestination
    def ReturnTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserGulliverShipDestination
    def ExportItemIdList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # UserGulliverShipDestination
    def ExportItemIdListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # UserGulliverShipDestination
    def ExportItemIdListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserGulliverShipDestination
    def ExportItemIdListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # UserGulliverShipDestination
    def ExportItemAmountList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # UserGulliverShipDestination
    def ExportItemAmountListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int16Flags, o)
        return 0

    # UserGulliverShipDestination
    def ExportItemAmountListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserGulliverShipDestination
    def ExportItemAmountListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # UserGulliverShipDestination
    def RewardItemBoxIdList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # UserGulliverShipDestination
    def RewardItemBoxIdListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # UserGulliverShipDestination
    def RewardItemBoxIdListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserGulliverShipDestination
    def RewardItemBoxIdListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # UserGulliverShipDestination
    def RewardItemBoxLotteryCountList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # UserGulliverShipDestination
    def RewardItemBoxLotteryCountListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int16Flags, o)
        return 0

    # UserGulliverShipDestination
    def RewardItemBoxLotteryCountListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserGulliverShipDestination
    def RewardItemBoxLotteryCountListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # UserGulliverShipDestination
    def RewardBoxTypeList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # UserGulliverShipDestination
    def RewardBoxTypeListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # UserGulliverShipDestination
    def RewardBoxTypeListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserGulliverShipDestination
    def RewardBoxTypeListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # UserGulliverShipDestination
    def RewardBoxLogList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # UserGulliverShipDestination
    def RewardBoxLogListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # UserGulliverShipDestination
    def RewardBoxLogListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserGulliverShipDestination
    def RewardBoxLogListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # UserGulliverShipDestination
    def RewardFirstItemBoxId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def UserGulliverShipDestinationStart(builder):
    builder.StartObject(10)

def Start(builder):
    UserGulliverShipDestinationStart(builder)

def UserGulliverShipDestinationAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserGulliverShipDestinationAddId(builder, id)

def UserGulliverShipDestinationAddDestinationId(builder, destinationId):
    builder.PrependUint32Slot(1, destinationId, 0)

def AddDestinationId(builder, destinationId):
    UserGulliverShipDestinationAddDestinationId(builder, destinationId)

def UserGulliverShipDestinationAddReturnTime(builder, returnTime):
    builder.PrependInt64Slot(2, returnTime, 0)

def AddReturnTime(builder, returnTime):
    UserGulliverShipDestinationAddReturnTime(builder, returnTime)

def UserGulliverShipDestinationAddExportItemIdList(builder, exportItemIdList):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(exportItemIdList), 0)

def AddExportItemIdList(builder, exportItemIdList):
    UserGulliverShipDestinationAddExportItemIdList(builder, exportItemIdList)

def UserGulliverShipDestinationStartExportItemIdListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartExportItemIdListVector(builder, numElems):
    return UserGulliverShipDestinationStartExportItemIdListVector(builder, numElems)

def UserGulliverShipDestinationAddExportItemAmountList(builder, exportItemAmountList):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(exportItemAmountList), 0)

def AddExportItemAmountList(builder, exportItemAmountList):
    UserGulliverShipDestinationAddExportItemAmountList(builder, exportItemAmountList)

def UserGulliverShipDestinationStartExportItemAmountListVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartExportItemAmountListVector(builder, numElems):
    return UserGulliverShipDestinationStartExportItemAmountListVector(builder, numElems)

def UserGulliverShipDestinationAddRewardItemBoxIdList(builder, rewardItemBoxIdList):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(rewardItemBoxIdList), 0)

def AddRewardItemBoxIdList(builder, rewardItemBoxIdList):
    UserGulliverShipDestinationAddRewardItemBoxIdList(builder, rewardItemBoxIdList)

def UserGulliverShipDestinationStartRewardItemBoxIdListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRewardItemBoxIdListVector(builder, numElems):
    return UserGulliverShipDestinationStartRewardItemBoxIdListVector(builder, numElems)

def UserGulliverShipDestinationAddRewardItemBoxLotteryCountList(builder, rewardItemBoxLotteryCountList):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(rewardItemBoxLotteryCountList), 0)

def AddRewardItemBoxLotteryCountList(builder, rewardItemBoxLotteryCountList):
    UserGulliverShipDestinationAddRewardItemBoxLotteryCountList(builder, rewardItemBoxLotteryCountList)

def UserGulliverShipDestinationStartRewardItemBoxLotteryCountListVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartRewardItemBoxLotteryCountListVector(builder, numElems):
    return UserGulliverShipDestinationStartRewardItemBoxLotteryCountListVector(builder, numElems)

def UserGulliverShipDestinationAddRewardBoxTypeList(builder, rewardBoxTypeList):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(rewardBoxTypeList), 0)

def AddRewardBoxTypeList(builder, rewardBoxTypeList):
    UserGulliverShipDestinationAddRewardBoxTypeList(builder, rewardBoxTypeList)

def UserGulliverShipDestinationStartRewardBoxTypeListVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartRewardBoxTypeListVector(builder, numElems):
    return UserGulliverShipDestinationStartRewardBoxTypeListVector(builder, numElems)

def UserGulliverShipDestinationAddRewardBoxLogList(builder, rewardBoxLogList):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(rewardBoxLogList), 0)

def AddRewardBoxLogList(builder, rewardBoxLogList):
    UserGulliverShipDestinationAddRewardBoxLogList(builder, rewardBoxLogList)

def UserGulliverShipDestinationStartRewardBoxLogListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRewardBoxLogListVector(builder, numElems):
    return UserGulliverShipDestinationStartRewardBoxLogListVector(builder, numElems)

def UserGulliverShipDestinationAddRewardFirstItemBoxId(builder, rewardFirstItemBoxId):
    builder.PrependUint32Slot(9, rewardFirstItemBoxId, 0)

def AddRewardFirstItemBoxId(builder, rewardFirstItemBoxId):
    UserGulliverShipDestinationAddRewardFirstItemBoxId(builder, rewardFirstItemBoxId)

def UserGulliverShipDestinationEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserGulliverShipDestinationEnd(builder)
