# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserPaymentRecommendOneSlotSetElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserPaymentRecommendOneSlotSetElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserPaymentRecommendOneSlotSetElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserPaymentRecommendOneSlotSetElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserPaymentRecommendOneSlotSetElement
    def RecommendId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserPaymentRecommendOneSlotSetElement
    def ShowLastAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def UserPaymentRecommendOneSlotSetElementStart(builder):
    builder.StartObject(2)

def Start(builder):
    UserPaymentRecommendOneSlotSetElementStart(builder)

def UserPaymentRecommendOneSlotSetElementAddRecommendId(builder, recommendId):
    builder.PrependUint32Slot(0, recommendId, 0)

def AddRecommendId(builder, recommendId):
    UserPaymentRecommendOneSlotSetElementAddRecommendId(builder, recommendId)

def UserPaymentRecommendOneSlotSetElementAddShowLastAt(builder, showLastAt):
    builder.PrependInt64Slot(1, showLastAt, 0)

def AddShowLastAt(builder, showLastAt):
    UserPaymentRecommendOneSlotSetElementAddShowLastAt(builder, showLastAt)

def UserPaymentRecommendOneSlotSetElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserPaymentRecommendOneSlotSetElementEnd(builder)
