# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserCraftCampaignRecipeCheckSetElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserCraftCampaignRecipeCheckSetElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserCraftCampaignRecipeCheckSetElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserCraftCampaignRecipeCheckSetElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserCraftCampaignRecipeCheckSetElement
    def RecordId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserCraftCampaignRecipeCheckSetElement
    def CampaignId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserCraftCampaignRecipeCheckSetElement
    def RecordType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def UserCraftCampaignRecipeCheckSetElementStart(builder):
    builder.StartObject(3)

def Start(builder):
    UserCraftCampaignRecipeCheckSetElementStart(builder)

def UserCraftCampaignRecipeCheckSetElementAddRecordId(builder, recordId):
    builder.PrependUint32Slot(0, recordId, 0)

def AddRecordId(builder, recordId):
    UserCraftCampaignRecipeCheckSetElementAddRecordId(builder, recordId)

def UserCraftCampaignRecipeCheckSetElementAddCampaignId(builder, campaignId):
    builder.PrependUint32Slot(1, campaignId, 0)

def AddCampaignId(builder, campaignId):
    UserCraftCampaignRecipeCheckSetElementAddCampaignId(builder, campaignId)

def UserCraftCampaignRecipeCheckSetElementAddRecordType(builder, recordType):
    builder.PrependInt32Slot(2, recordType, 0)

def AddRecordType(builder, recordType):
    UserCraftCampaignRecipeCheckSetElementAddRecordType(builder, recordType)

def UserCraftCampaignRecipeCheckSetElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserCraftCampaignRecipeCheckSetElementEnd(builder)
