# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserAdventureMapAchievedSquareSetElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserAdventureMapAchievedSquareSetElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserAdventureMapAchievedSquareSetElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserAdventureMapAchievedSquareSetElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserAdventureMapAchievedSquareSetElement
    def SquareSetId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def UserAdventureMapAchievedSquareSetElementStart(builder):
    builder.StartObject(1)

def Start(builder):
    UserAdventureMapAchievedSquareSetElementStart(builder)

def UserAdventureMapAchievedSquareSetElementAddSquareSetId(builder, squareSetId):
    builder.PrependUint32Slot(0, squareSetId, 0)

def AddSquareSetId(builder, squareSetId):
    UserAdventureMapAchievedSquareSetElementAddSquareSetId(builder, squareSetId)

def UserAdventureMapAchievedSquareSetElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserAdventureMapAchievedSquareSetElementEnd(builder)
