# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserUIMsg(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserUIMsg()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserUIMsg(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserUIMsg
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserUIMsg
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def SzaTalked(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def CwcTalked(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenLoanMenu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def DonationFirstTalk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def LoanTalkFlag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def IsAchievementNew(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def DoneSmartphoneOpened(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def DoneCabconRelease(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def DoneSpecialCustomize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def CwbTalked(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def SecondCarTalked(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenBazaarMenu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenCatalogMenu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenFriendMenu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def SecondCarCwbTalked(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsUnlockedLObj(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsVisitedOtherPlayerCampsite(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsUsedCameraModeInCampsite(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenMineDepartureDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsVisitedMyCampsiteAfterTutorial(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsOccuredSelfishQuest(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsTerminatedNpcQuest(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenAchievement(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenNpcReplace(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenLayoutEditInCar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def CraftAlwTalked(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenOkGameMachine(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenNpcChangeClothes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenLandformCustom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenQuestRetire(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def PresentBalloonLastAddedUtcTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def ShowSendAnimalAfterCatchAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def IsFortuneCookieShopFirstMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsNewCookieArrivalEventOneDay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsFortuneCookiePointExchangeFirstMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def LastCampaignIdSeenAtForutneCookieShop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def IsSeenMessageAfterFirstFortuneCookiePurchase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenNpcEpisodeManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def RecommendedHaniwaExchangeUtcTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def ShouldRecommendHaniwaExchange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenFortuneCookieShopManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(86))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenFortunePointExchangeManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenMyPhotoRegistrationManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenSpecialtyFruitsManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(92))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenFacilityBalloonShopManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(94))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenFurniturePuzzleFailedResultManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(96))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenRevivalTutorial(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(98))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def CarRugPutAwayNotice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(100))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenMembershipStartDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenFirstStoreHouse(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(104))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenCottageSecondFloorManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(106))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenClaftPreviewManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(108))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenMembershipRenewalDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(110))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenCraftMenuToPreviewManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(112))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def MapMenuSeenUtcTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(114))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def IsSeenMyCoordinateManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(116))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def GardeningExchangeMenuSeenUtcTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(118))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def GardeningSeedShopMenuSeenUtcTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(120))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def IsSeenAlbumMenu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(122))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenFriendGiftMenu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(124))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenMenbershipFreeTrialNotice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(126))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenMenbershipFreeTrialEndNotice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(128))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsNewMembershipServeceEnd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(130))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenArCottageCautionDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(132))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenArCameraCautionDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(134))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenArAppealDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(136))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def SeenPersonalGuideCampaignIdList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(138))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # UserUIMsg
    def SeenPersonalGuideCampaignIdListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(138))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # UserUIMsg
    def SeenPersonalGuideCampaignIdListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(138))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserUIMsg
    def SeenPersonalGuideCampaignIdListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(138))
        return o == 0

    # UserUIMsg
    def PersonalGuideCampaignIdFromServerCheckList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(140))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # UserUIMsg
    def PersonalGuideCampaignIdFromServerCheckListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(140))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # UserUIMsg
    def PersonalGuideCampaignIdFromServerCheckListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(140))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserUIMsg
    def PersonalGuideCampaignIdFromServerCheckListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(140))
        return o == 0

    # UserUIMsg
    def CheckServerPersonalGuideTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(142))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def SeenPersonalGuideTimeList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(144))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # UserUIMsg
    def SeenPersonalGuideTimeListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(144))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # UserUIMsg
    def SeenPersonalGuideTimeListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(144))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserUIMsg
    def SeenPersonalGuideTimeListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(144))
        return o == 0

    # UserUIMsg
    def ForcedInformationListAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(146))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def SeenTreasureEventCampaignId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(148))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def IsSeenArPresetCautionDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(150))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenNpcReplaceDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(152))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def ReplaceEmptyState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(154))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def IsSeenPanelMissionManual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(156))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsCottageAssemble(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(158))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsPartsTicketNew(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(160))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def StorehouseGuideConditionNumFurniture(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(162))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def StorehouseGuideConditionNumClothes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(164))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def IsSeenNpcReplaceShuffle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(166))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenCookieExchangeDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(168))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenMySetHelp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(170))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def ExchangeResourceResetTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(172))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserUIMsg
    def ExchangeResourceCountList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(174))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # UserUIMsg
    def ExchangeResourceCountListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(174))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # UserUIMsg
    def ExchangeResourceCountListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(174))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserUIMsg
    def ExchangeResourceCountListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(174))
        return o == 0

    # UserUIMsg
    def IsSeenMyDesignHelp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(176))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsHandoverFromOnToOff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(178))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenReafstoneExchangeMonth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(180))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsSeenCatalogCompleteDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(182))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsNeedNewCatalogCompleteDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(184))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserUIMsg
    def IsNeedNewCookieExchangeDialog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(186))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def UserUIMsgStart(builder):
    builder.StartObject(92)

def Start(builder):
    UserUIMsgStart(builder)

def UserUIMsgAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserUIMsgAddId(builder, id)

def UserUIMsgAddSzaTalked(builder, szaTalked):
    builder.PrependBoolSlot(1, szaTalked, 0)

def AddSzaTalked(builder, szaTalked):
    UserUIMsgAddSzaTalked(builder, szaTalked)

def UserUIMsgAddCwcTalked(builder, cwcTalked):
    builder.PrependBoolSlot(2, cwcTalked, 0)

def AddCwcTalked(builder, cwcTalked):
    UserUIMsgAddCwcTalked(builder, cwcTalked)

def UserUIMsgAddIsSeenLoanMenu(builder, isSeenLoanMenu):
    builder.PrependBoolSlot(3, isSeenLoanMenu, 0)

def AddIsSeenLoanMenu(builder, isSeenLoanMenu):
    UserUIMsgAddIsSeenLoanMenu(builder, isSeenLoanMenu)

def UserUIMsgAddDonationFirstTalk(builder, donationFirstTalk):
    builder.PrependBoolSlot(4, donationFirstTalk, 0)

def AddDonationFirstTalk(builder, donationFirstTalk):
    UserUIMsgAddDonationFirstTalk(builder, donationFirstTalk)

def UserUIMsgAddLoanTalkFlag(builder, loanTalkFlag):
    builder.PrependInt32Slot(5, loanTalkFlag, 0)

def AddLoanTalkFlag(builder, loanTalkFlag):
    UserUIMsgAddLoanTalkFlag(builder, loanTalkFlag)

def UserUIMsgAddIsAchievementNew(builder, isAchievementNew):
    builder.PrependBoolSlot(6, isAchievementNew, 0)

def AddIsAchievementNew(builder, isAchievementNew):
    UserUIMsgAddIsAchievementNew(builder, isAchievementNew)

def UserUIMsgAddDoneSmartphoneOpened(builder, doneSmartphoneOpened):
    builder.PrependBoolSlot(7, doneSmartphoneOpened, 0)

def AddDoneSmartphoneOpened(builder, doneSmartphoneOpened):
    UserUIMsgAddDoneSmartphoneOpened(builder, doneSmartphoneOpened)

def UserUIMsgAddDoneCabconRelease(builder, doneCabconRelease):
    builder.PrependBoolSlot(8, doneCabconRelease, 0)

def AddDoneCabconRelease(builder, doneCabconRelease):
    UserUIMsgAddDoneCabconRelease(builder, doneCabconRelease)

def UserUIMsgAddDoneSpecialCustomize(builder, doneSpecialCustomize):
    builder.PrependBoolSlot(9, doneSpecialCustomize, 0)

def AddDoneSpecialCustomize(builder, doneSpecialCustomize):
    UserUIMsgAddDoneSpecialCustomize(builder, doneSpecialCustomize)

def UserUIMsgAddCwbTalked(builder, cwbTalked):
    builder.PrependBoolSlot(10, cwbTalked, 0)

def AddCwbTalked(builder, cwbTalked):
    UserUIMsgAddCwbTalked(builder, cwbTalked)

def UserUIMsgAddSecondCarTalked(builder, secondCarTalked):
    builder.PrependBoolSlot(11, secondCarTalked, 0)

def AddSecondCarTalked(builder, secondCarTalked):
    UserUIMsgAddSecondCarTalked(builder, secondCarTalked)

def UserUIMsgAddIsSeenBazaarMenu(builder, isSeenBazaarMenu):
    builder.PrependBoolSlot(12, isSeenBazaarMenu, 0)

def AddIsSeenBazaarMenu(builder, isSeenBazaarMenu):
    UserUIMsgAddIsSeenBazaarMenu(builder, isSeenBazaarMenu)

def UserUIMsgAddIsSeenCatalogMenu(builder, isSeenCatalogMenu):
    builder.PrependBoolSlot(13, isSeenCatalogMenu, 0)

def AddIsSeenCatalogMenu(builder, isSeenCatalogMenu):
    UserUIMsgAddIsSeenCatalogMenu(builder, isSeenCatalogMenu)

def UserUIMsgAddIsSeenFriendMenu(builder, isSeenFriendMenu):
    builder.PrependBoolSlot(14, isSeenFriendMenu, 0)

def AddIsSeenFriendMenu(builder, isSeenFriendMenu):
    UserUIMsgAddIsSeenFriendMenu(builder, isSeenFriendMenu)

def UserUIMsgAddSecondCarCwbTalked(builder, secondCarCwbTalked):
    builder.PrependBoolSlot(15, secondCarCwbTalked, 0)

def AddSecondCarCwbTalked(builder, secondCarCwbTalked):
    UserUIMsgAddSecondCarCwbTalked(builder, secondCarCwbTalked)

def UserUIMsgAddIsUnlockedLObj(builder, isUnlockedLObj):
    builder.PrependBoolSlot(16, isUnlockedLObj, 0)

def AddIsUnlockedLObj(builder, isUnlockedLObj):
    UserUIMsgAddIsUnlockedLObj(builder, isUnlockedLObj)

def UserUIMsgAddIsVisitedOtherPlayerCampsite(builder, isVisitedOtherPlayerCampsite):
    builder.PrependBoolSlot(17, isVisitedOtherPlayerCampsite, 0)

def AddIsVisitedOtherPlayerCampsite(builder, isVisitedOtherPlayerCampsite):
    UserUIMsgAddIsVisitedOtherPlayerCampsite(builder, isVisitedOtherPlayerCampsite)

def UserUIMsgAddIsUsedCameraModeInCampsite(builder, isUsedCameraModeInCampsite):
    builder.PrependBoolSlot(18, isUsedCameraModeInCampsite, 0)

def AddIsUsedCameraModeInCampsite(builder, isUsedCameraModeInCampsite):
    UserUIMsgAddIsUsedCameraModeInCampsite(builder, isUsedCameraModeInCampsite)

def UserUIMsgAddIsSeenMineDepartureDialog(builder, isSeenMineDepartureDialog):
    builder.PrependBoolSlot(19, isSeenMineDepartureDialog, 0)

def AddIsSeenMineDepartureDialog(builder, isSeenMineDepartureDialog):
    UserUIMsgAddIsSeenMineDepartureDialog(builder, isSeenMineDepartureDialog)

def UserUIMsgAddIsVisitedMyCampsiteAfterTutorial(builder, isVisitedMyCampsiteAfterTutorial):
    builder.PrependBoolSlot(20, isVisitedMyCampsiteAfterTutorial, 0)

def AddIsVisitedMyCampsiteAfterTutorial(builder, isVisitedMyCampsiteAfterTutorial):
    UserUIMsgAddIsVisitedMyCampsiteAfterTutorial(builder, isVisitedMyCampsiteAfterTutorial)

def UserUIMsgAddIsOccuredSelfishQuest(builder, isOccuredSelfishQuest):
    builder.PrependBoolSlot(21, isOccuredSelfishQuest, 0)

def AddIsOccuredSelfishQuest(builder, isOccuredSelfishQuest):
    UserUIMsgAddIsOccuredSelfishQuest(builder, isOccuredSelfishQuest)

def UserUIMsgAddIsTerminatedNpcQuest(builder, isTerminatedNpcQuest):
    builder.PrependBoolSlot(22, isTerminatedNpcQuest, 0)

def AddIsTerminatedNpcQuest(builder, isTerminatedNpcQuest):
    UserUIMsgAddIsTerminatedNpcQuest(builder, isTerminatedNpcQuest)

def UserUIMsgAddIsSeenAchievement(builder, isSeenAchievement):
    builder.PrependBoolSlot(23, isSeenAchievement, 0)

def AddIsSeenAchievement(builder, isSeenAchievement):
    UserUIMsgAddIsSeenAchievement(builder, isSeenAchievement)

def UserUIMsgAddIsSeenNpcReplace(builder, isSeenNpcReplace):
    builder.PrependBoolSlot(24, isSeenNpcReplace, 0)

def AddIsSeenNpcReplace(builder, isSeenNpcReplace):
    UserUIMsgAddIsSeenNpcReplace(builder, isSeenNpcReplace)

def UserUIMsgAddIsSeenLayoutEditInCar(builder, isSeenLayoutEditInCar):
    builder.PrependBoolSlot(25, isSeenLayoutEditInCar, 0)

def AddIsSeenLayoutEditInCar(builder, isSeenLayoutEditInCar):
    UserUIMsgAddIsSeenLayoutEditInCar(builder, isSeenLayoutEditInCar)

def UserUIMsgAddCraftAlwTalked(builder, craftAlwTalked):
    builder.PrependBoolSlot(26, craftAlwTalked, 0)

def AddCraftAlwTalked(builder, craftAlwTalked):
    UserUIMsgAddCraftAlwTalked(builder, craftAlwTalked)

def UserUIMsgAddIsSeenOkGameMachine(builder, isSeenOkGameMachine):
    builder.PrependBoolSlot(27, isSeenOkGameMachine, 0)

def AddIsSeenOkGameMachine(builder, isSeenOkGameMachine):
    UserUIMsgAddIsSeenOkGameMachine(builder, isSeenOkGameMachine)

def UserUIMsgAddIsSeenNpcChangeClothes(builder, isSeenNpcChangeClothes):
    builder.PrependBoolSlot(28, isSeenNpcChangeClothes, 0)

def AddIsSeenNpcChangeClothes(builder, isSeenNpcChangeClothes):
    UserUIMsgAddIsSeenNpcChangeClothes(builder, isSeenNpcChangeClothes)

def UserUIMsgAddIsSeenLandformCustom(builder, isSeenLandformCustom):
    builder.PrependBoolSlot(29, isSeenLandformCustom, 0)

def AddIsSeenLandformCustom(builder, isSeenLandformCustom):
    UserUIMsgAddIsSeenLandformCustom(builder, isSeenLandformCustom)

def UserUIMsgAddIsSeenQuestRetire(builder, isSeenQuestRetire):
    builder.PrependBoolSlot(30, isSeenQuestRetire, 0)

def AddIsSeenQuestRetire(builder, isSeenQuestRetire):
    UserUIMsgAddIsSeenQuestRetire(builder, isSeenQuestRetire)

def UserUIMsgAddPresentBalloonLastAddedUtcTime(builder, presentBalloonLastAddedUtcTime):
    builder.PrependInt64Slot(31, presentBalloonLastAddedUtcTime, 0)

def AddPresentBalloonLastAddedUtcTime(builder, presentBalloonLastAddedUtcTime):
    UserUIMsgAddPresentBalloonLastAddedUtcTime(builder, presentBalloonLastAddedUtcTime)

def UserUIMsgAddShowSendAnimalAfterCatchAt(builder, showSendAnimalAfterCatchAt):
    builder.PrependInt64Slot(32, showSendAnimalAfterCatchAt, 0)

def AddShowSendAnimalAfterCatchAt(builder, showSendAnimalAfterCatchAt):
    UserUIMsgAddShowSendAnimalAfterCatchAt(builder, showSendAnimalAfterCatchAt)

def UserUIMsgAddIsFortuneCookieShopFirstMessage(builder, isFortuneCookieShopFirstMessage):
    builder.PrependBoolSlot(33, isFortuneCookieShopFirstMessage, 0)

def AddIsFortuneCookieShopFirstMessage(builder, isFortuneCookieShopFirstMessage):
    UserUIMsgAddIsFortuneCookieShopFirstMessage(builder, isFortuneCookieShopFirstMessage)

def UserUIMsgAddIsNewCookieArrivalEventOneDay(builder, isNewCookieArrivalEventOneDay):
    builder.PrependBoolSlot(34, isNewCookieArrivalEventOneDay, 0)

def AddIsNewCookieArrivalEventOneDay(builder, isNewCookieArrivalEventOneDay):
    UserUIMsgAddIsNewCookieArrivalEventOneDay(builder, isNewCookieArrivalEventOneDay)

def UserUIMsgAddIsFortuneCookiePointExchangeFirstMessage(builder, isFortuneCookiePointExchangeFirstMessage):
    builder.PrependBoolSlot(35, isFortuneCookiePointExchangeFirstMessage, 0)

def AddIsFortuneCookiePointExchangeFirstMessage(builder, isFortuneCookiePointExchangeFirstMessage):
    UserUIMsgAddIsFortuneCookiePointExchangeFirstMessage(builder, isFortuneCookiePointExchangeFirstMessage)

def UserUIMsgAddLastCampaignIdSeenAtForutneCookieShop(builder, lastCampaignIdSeenAtForutneCookieShop):
    builder.PrependUint32Slot(36, lastCampaignIdSeenAtForutneCookieShop, 0)

def AddLastCampaignIdSeenAtForutneCookieShop(builder, lastCampaignIdSeenAtForutneCookieShop):
    UserUIMsgAddLastCampaignIdSeenAtForutneCookieShop(builder, lastCampaignIdSeenAtForutneCookieShop)

def UserUIMsgAddIsSeenMessageAfterFirstFortuneCookiePurchase(builder, isSeenMessageAfterFirstFortuneCookiePurchase):
    builder.PrependBoolSlot(37, isSeenMessageAfterFirstFortuneCookiePurchase, 0)

def AddIsSeenMessageAfterFirstFortuneCookiePurchase(builder, isSeenMessageAfterFirstFortuneCookiePurchase):
    UserUIMsgAddIsSeenMessageAfterFirstFortuneCookiePurchase(builder, isSeenMessageAfterFirstFortuneCookiePurchase)

def UserUIMsgAddIsSeenNpcEpisodeManual(builder, isSeenNpcEpisodeManual):
    builder.PrependBoolSlot(38, isSeenNpcEpisodeManual, 0)

def AddIsSeenNpcEpisodeManual(builder, isSeenNpcEpisodeManual):
    UserUIMsgAddIsSeenNpcEpisodeManual(builder, isSeenNpcEpisodeManual)

def UserUIMsgAddRecommendedHaniwaExchangeUtcTime(builder, recommendedHaniwaExchangeUtcTime):
    builder.PrependInt64Slot(39, recommendedHaniwaExchangeUtcTime, 0)

def AddRecommendedHaniwaExchangeUtcTime(builder, recommendedHaniwaExchangeUtcTime):
    UserUIMsgAddRecommendedHaniwaExchangeUtcTime(builder, recommendedHaniwaExchangeUtcTime)

def UserUIMsgAddShouldRecommendHaniwaExchange(builder, shouldRecommendHaniwaExchange):
    builder.PrependBoolSlot(40, shouldRecommendHaniwaExchange, 0)

def AddShouldRecommendHaniwaExchange(builder, shouldRecommendHaniwaExchange):
    UserUIMsgAddShouldRecommendHaniwaExchange(builder, shouldRecommendHaniwaExchange)

def UserUIMsgAddIsSeenFortuneCookieShopManual(builder, isSeenFortuneCookieShopManual):
    builder.PrependBoolSlot(41, isSeenFortuneCookieShopManual, 0)

def AddIsSeenFortuneCookieShopManual(builder, isSeenFortuneCookieShopManual):
    UserUIMsgAddIsSeenFortuneCookieShopManual(builder, isSeenFortuneCookieShopManual)

def UserUIMsgAddIsSeenFortunePointExchangeManual(builder, isSeenFortunePointExchangeManual):
    builder.PrependBoolSlot(42, isSeenFortunePointExchangeManual, 0)

def AddIsSeenFortunePointExchangeManual(builder, isSeenFortunePointExchangeManual):
    UserUIMsgAddIsSeenFortunePointExchangeManual(builder, isSeenFortunePointExchangeManual)

def UserUIMsgAddIsSeenMyPhotoRegistrationManual(builder, isSeenMyPhotoRegistrationManual):
    builder.PrependBoolSlot(43, isSeenMyPhotoRegistrationManual, 0)

def AddIsSeenMyPhotoRegistrationManual(builder, isSeenMyPhotoRegistrationManual):
    UserUIMsgAddIsSeenMyPhotoRegistrationManual(builder, isSeenMyPhotoRegistrationManual)

def UserUIMsgAddIsSeenSpecialtyFruitsManual(builder, isSeenSpecialtyFruitsManual):
    builder.PrependBoolSlot(44, isSeenSpecialtyFruitsManual, 0)

def AddIsSeenSpecialtyFruitsManual(builder, isSeenSpecialtyFruitsManual):
    UserUIMsgAddIsSeenSpecialtyFruitsManual(builder, isSeenSpecialtyFruitsManual)

def UserUIMsgAddIsSeenFacilityBalloonShopManual(builder, isSeenFacilityBalloonShopManual):
    builder.PrependBoolSlot(45, isSeenFacilityBalloonShopManual, 0)

def AddIsSeenFacilityBalloonShopManual(builder, isSeenFacilityBalloonShopManual):
    UserUIMsgAddIsSeenFacilityBalloonShopManual(builder, isSeenFacilityBalloonShopManual)

def UserUIMsgAddIsSeenFurniturePuzzleFailedResultManual(builder, isSeenFurniturePuzzleFailedResultManual):
    builder.PrependBoolSlot(46, isSeenFurniturePuzzleFailedResultManual, 0)

def AddIsSeenFurniturePuzzleFailedResultManual(builder, isSeenFurniturePuzzleFailedResultManual):
    UserUIMsgAddIsSeenFurniturePuzzleFailedResultManual(builder, isSeenFurniturePuzzleFailedResultManual)

def UserUIMsgAddIsSeenRevivalTutorial(builder, isSeenRevivalTutorial):
    builder.PrependBoolSlot(47, isSeenRevivalTutorial, 0)

def AddIsSeenRevivalTutorial(builder, isSeenRevivalTutorial):
    UserUIMsgAddIsSeenRevivalTutorial(builder, isSeenRevivalTutorial)

def UserUIMsgAddCarRugPutAwayNotice(builder, carRugPutAwayNotice):
    builder.PrependBoolSlot(48, carRugPutAwayNotice, 0)

def AddCarRugPutAwayNotice(builder, carRugPutAwayNotice):
    UserUIMsgAddCarRugPutAwayNotice(builder, carRugPutAwayNotice)

def UserUIMsgAddIsSeenMembershipStartDialog(builder, isSeenMembershipStartDialog):
    builder.PrependBoolSlot(49, isSeenMembershipStartDialog, 0)

def AddIsSeenMembershipStartDialog(builder, isSeenMembershipStartDialog):
    UserUIMsgAddIsSeenMembershipStartDialog(builder, isSeenMembershipStartDialog)

def UserUIMsgAddIsSeenFirstStoreHouse(builder, isSeenFirstStoreHouse):
    builder.PrependBoolSlot(50, isSeenFirstStoreHouse, 0)

def AddIsSeenFirstStoreHouse(builder, isSeenFirstStoreHouse):
    UserUIMsgAddIsSeenFirstStoreHouse(builder, isSeenFirstStoreHouse)

def UserUIMsgAddIsSeenCottageSecondFloorManual(builder, isSeenCottageSecondFloorManual):
    builder.PrependBoolSlot(51, isSeenCottageSecondFloorManual, 0)

def AddIsSeenCottageSecondFloorManual(builder, isSeenCottageSecondFloorManual):
    UserUIMsgAddIsSeenCottageSecondFloorManual(builder, isSeenCottageSecondFloorManual)

def UserUIMsgAddIsSeenClaftPreviewManual(builder, isSeenClaftPreviewManual):
    builder.PrependBoolSlot(52, isSeenClaftPreviewManual, 0)

def AddIsSeenClaftPreviewManual(builder, isSeenClaftPreviewManual):
    UserUIMsgAddIsSeenClaftPreviewManual(builder, isSeenClaftPreviewManual)

def UserUIMsgAddIsSeenMembershipRenewalDialog(builder, isSeenMembershipRenewalDialog):
    builder.PrependBoolSlot(53, isSeenMembershipRenewalDialog, 0)

def AddIsSeenMembershipRenewalDialog(builder, isSeenMembershipRenewalDialog):
    UserUIMsgAddIsSeenMembershipRenewalDialog(builder, isSeenMembershipRenewalDialog)

def UserUIMsgAddIsSeenCraftMenuToPreviewManual(builder, isSeenCraftMenuToPreviewManual):
    builder.PrependBoolSlot(54, isSeenCraftMenuToPreviewManual, 0)

def AddIsSeenCraftMenuToPreviewManual(builder, isSeenCraftMenuToPreviewManual):
    UserUIMsgAddIsSeenCraftMenuToPreviewManual(builder, isSeenCraftMenuToPreviewManual)

def UserUIMsgAddMapMenuSeenUtcTime(builder, mapMenuSeenUtcTime):
    builder.PrependInt64Slot(55, mapMenuSeenUtcTime, 0)

def AddMapMenuSeenUtcTime(builder, mapMenuSeenUtcTime):
    UserUIMsgAddMapMenuSeenUtcTime(builder, mapMenuSeenUtcTime)

def UserUIMsgAddIsSeenMyCoordinateManual(builder, isSeenMyCoordinateManual):
    builder.PrependBoolSlot(56, isSeenMyCoordinateManual, 0)

def AddIsSeenMyCoordinateManual(builder, isSeenMyCoordinateManual):
    UserUIMsgAddIsSeenMyCoordinateManual(builder, isSeenMyCoordinateManual)

def UserUIMsgAddGardeningExchangeMenuSeenUtcTime(builder, gardeningExchangeMenuSeenUtcTime):
    builder.PrependInt64Slot(57, gardeningExchangeMenuSeenUtcTime, 0)

def AddGardeningExchangeMenuSeenUtcTime(builder, gardeningExchangeMenuSeenUtcTime):
    UserUIMsgAddGardeningExchangeMenuSeenUtcTime(builder, gardeningExchangeMenuSeenUtcTime)

def UserUIMsgAddGardeningSeedShopMenuSeenUtcTime(builder, gardeningSeedShopMenuSeenUtcTime):
    builder.PrependInt64Slot(58, gardeningSeedShopMenuSeenUtcTime, 0)

def AddGardeningSeedShopMenuSeenUtcTime(builder, gardeningSeedShopMenuSeenUtcTime):
    UserUIMsgAddGardeningSeedShopMenuSeenUtcTime(builder, gardeningSeedShopMenuSeenUtcTime)

def UserUIMsgAddIsSeenAlbumMenu(builder, isSeenAlbumMenu):
    builder.PrependBoolSlot(59, isSeenAlbumMenu, 0)

def AddIsSeenAlbumMenu(builder, isSeenAlbumMenu):
    UserUIMsgAddIsSeenAlbumMenu(builder, isSeenAlbumMenu)

def UserUIMsgAddIsSeenFriendGiftMenu(builder, isSeenFriendGiftMenu):
    builder.PrependBoolSlot(60, isSeenFriendGiftMenu, 0)

def AddIsSeenFriendGiftMenu(builder, isSeenFriendGiftMenu):
    UserUIMsgAddIsSeenFriendGiftMenu(builder, isSeenFriendGiftMenu)

def UserUIMsgAddIsSeenMenbershipFreeTrialNotice(builder, isSeenMenbershipFreeTrialNotice):
    builder.PrependBoolSlot(61, isSeenMenbershipFreeTrialNotice, 0)

def AddIsSeenMenbershipFreeTrialNotice(builder, isSeenMenbershipFreeTrialNotice):
    UserUIMsgAddIsSeenMenbershipFreeTrialNotice(builder, isSeenMenbershipFreeTrialNotice)

def UserUIMsgAddIsSeenMenbershipFreeTrialEndNotice(builder, isSeenMenbershipFreeTrialEndNotice):
    builder.PrependBoolSlot(62, isSeenMenbershipFreeTrialEndNotice, 0)

def AddIsSeenMenbershipFreeTrialEndNotice(builder, isSeenMenbershipFreeTrialEndNotice):
    UserUIMsgAddIsSeenMenbershipFreeTrialEndNotice(builder, isSeenMenbershipFreeTrialEndNotice)

def UserUIMsgAddIsNewMembershipServeceEnd(builder, isNewMembershipServeceEnd):
    builder.PrependBoolSlot(63, isNewMembershipServeceEnd, 0)

def AddIsNewMembershipServeceEnd(builder, isNewMembershipServeceEnd):
    UserUIMsgAddIsNewMembershipServeceEnd(builder, isNewMembershipServeceEnd)

def UserUIMsgAddIsSeenArCottageCautionDialog(builder, isSeenArCottageCautionDialog):
    builder.PrependBoolSlot(64, isSeenArCottageCautionDialog, 0)

def AddIsSeenArCottageCautionDialog(builder, isSeenArCottageCautionDialog):
    UserUIMsgAddIsSeenArCottageCautionDialog(builder, isSeenArCottageCautionDialog)

def UserUIMsgAddIsSeenArCameraCautionDialog(builder, isSeenArCameraCautionDialog):
    builder.PrependBoolSlot(65, isSeenArCameraCautionDialog, 0)

def AddIsSeenArCameraCautionDialog(builder, isSeenArCameraCautionDialog):
    UserUIMsgAddIsSeenArCameraCautionDialog(builder, isSeenArCameraCautionDialog)

def UserUIMsgAddIsSeenArAppealDialog(builder, isSeenArAppealDialog):
    builder.PrependBoolSlot(66, isSeenArAppealDialog, 0)

def AddIsSeenArAppealDialog(builder, isSeenArAppealDialog):
    UserUIMsgAddIsSeenArAppealDialog(builder, isSeenArAppealDialog)

def UserUIMsgAddSeenPersonalGuideCampaignIdList(builder, seenPersonalGuideCampaignIdList):
    builder.PrependUOffsetTRelativeSlot(67, flatbuffers.number_types.UOffsetTFlags.py_type(seenPersonalGuideCampaignIdList), 0)

def AddSeenPersonalGuideCampaignIdList(builder, seenPersonalGuideCampaignIdList):
    UserUIMsgAddSeenPersonalGuideCampaignIdList(builder, seenPersonalGuideCampaignIdList)

def UserUIMsgStartSeenPersonalGuideCampaignIdListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSeenPersonalGuideCampaignIdListVector(builder, numElems):
    return UserUIMsgStartSeenPersonalGuideCampaignIdListVector(builder, numElems)

def UserUIMsgAddPersonalGuideCampaignIdFromServerCheckList(builder, personalGuideCampaignIdFromServerCheckList):
    builder.PrependUOffsetTRelativeSlot(68, flatbuffers.number_types.UOffsetTFlags.py_type(personalGuideCampaignIdFromServerCheckList), 0)

def AddPersonalGuideCampaignIdFromServerCheckList(builder, personalGuideCampaignIdFromServerCheckList):
    UserUIMsgAddPersonalGuideCampaignIdFromServerCheckList(builder, personalGuideCampaignIdFromServerCheckList)

def UserUIMsgStartPersonalGuideCampaignIdFromServerCheckListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPersonalGuideCampaignIdFromServerCheckListVector(builder, numElems):
    return UserUIMsgStartPersonalGuideCampaignIdFromServerCheckListVector(builder, numElems)

def UserUIMsgAddCheckServerPersonalGuideTime(builder, checkServerPersonalGuideTime):
    builder.PrependInt64Slot(69, checkServerPersonalGuideTime, 0)

def AddCheckServerPersonalGuideTime(builder, checkServerPersonalGuideTime):
    UserUIMsgAddCheckServerPersonalGuideTime(builder, checkServerPersonalGuideTime)

def UserUIMsgAddSeenPersonalGuideTimeList(builder, seenPersonalGuideTimeList):
    builder.PrependUOffsetTRelativeSlot(70, flatbuffers.number_types.UOffsetTFlags.py_type(seenPersonalGuideTimeList), 0)

def AddSeenPersonalGuideTimeList(builder, seenPersonalGuideTimeList):
    UserUIMsgAddSeenPersonalGuideTimeList(builder, seenPersonalGuideTimeList)

def UserUIMsgStartSeenPersonalGuideTimeListVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartSeenPersonalGuideTimeListVector(builder, numElems):
    return UserUIMsgStartSeenPersonalGuideTimeListVector(builder, numElems)

def UserUIMsgAddForcedInformationListAt(builder, forcedInformationListAt):
    builder.PrependInt64Slot(71, forcedInformationListAt, 0)

def AddForcedInformationListAt(builder, forcedInformationListAt):
    UserUIMsgAddForcedInformationListAt(builder, forcedInformationListAt)

def UserUIMsgAddSeenTreasureEventCampaignId(builder, seenTreasureEventCampaignId):
    builder.PrependUint32Slot(72, seenTreasureEventCampaignId, 0)

def AddSeenTreasureEventCampaignId(builder, seenTreasureEventCampaignId):
    UserUIMsgAddSeenTreasureEventCampaignId(builder, seenTreasureEventCampaignId)

def UserUIMsgAddIsSeenArPresetCautionDialog(builder, isSeenArPresetCautionDialog):
    builder.PrependBoolSlot(73, isSeenArPresetCautionDialog, 0)

def AddIsSeenArPresetCautionDialog(builder, isSeenArPresetCautionDialog):
    UserUIMsgAddIsSeenArPresetCautionDialog(builder, isSeenArPresetCautionDialog)

def UserUIMsgAddIsSeenNpcReplaceDialog(builder, isSeenNpcReplaceDialog):
    builder.PrependBoolSlot(74, isSeenNpcReplaceDialog, 0)

def AddIsSeenNpcReplaceDialog(builder, isSeenNpcReplaceDialog):
    UserUIMsgAddIsSeenNpcReplaceDialog(builder, isSeenNpcReplaceDialog)

def UserUIMsgAddReplaceEmptyState(builder, replaceEmptyState):
    builder.PrependUint8Slot(75, replaceEmptyState, 0)

def AddReplaceEmptyState(builder, replaceEmptyState):
    UserUIMsgAddReplaceEmptyState(builder, replaceEmptyState)

def UserUIMsgAddIsSeenPanelMissionManual(builder, isSeenPanelMissionManual):
    builder.PrependBoolSlot(76, isSeenPanelMissionManual, 0)

def AddIsSeenPanelMissionManual(builder, isSeenPanelMissionManual):
    UserUIMsgAddIsSeenPanelMissionManual(builder, isSeenPanelMissionManual)

def UserUIMsgAddIsCottageAssemble(builder, isCottageAssemble):
    builder.PrependBoolSlot(77, isCottageAssemble, 0)

def AddIsCottageAssemble(builder, isCottageAssemble):
    UserUIMsgAddIsCottageAssemble(builder, isCottageAssemble)

def UserUIMsgAddIsPartsTicketNew(builder, isPartsTicketNew):
    builder.PrependBoolSlot(78, isPartsTicketNew, 0)

def AddIsPartsTicketNew(builder, isPartsTicketNew):
    UserUIMsgAddIsPartsTicketNew(builder, isPartsTicketNew)

def UserUIMsgAddStorehouseGuideConditionNumFurniture(builder, storehouseGuideConditionNumFurniture):
    builder.PrependInt32Slot(79, storehouseGuideConditionNumFurniture, 0)

def AddStorehouseGuideConditionNumFurniture(builder, storehouseGuideConditionNumFurniture):
    UserUIMsgAddStorehouseGuideConditionNumFurniture(builder, storehouseGuideConditionNumFurniture)

def UserUIMsgAddStorehouseGuideConditionNumClothes(builder, storehouseGuideConditionNumClothes):
    builder.PrependInt32Slot(80, storehouseGuideConditionNumClothes, 0)

def AddStorehouseGuideConditionNumClothes(builder, storehouseGuideConditionNumClothes):
    UserUIMsgAddStorehouseGuideConditionNumClothes(builder, storehouseGuideConditionNumClothes)

def UserUIMsgAddIsSeenNpcReplaceShuffle(builder, isSeenNpcReplaceShuffle):
    builder.PrependBoolSlot(81, isSeenNpcReplaceShuffle, 0)

def AddIsSeenNpcReplaceShuffle(builder, isSeenNpcReplaceShuffle):
    UserUIMsgAddIsSeenNpcReplaceShuffle(builder, isSeenNpcReplaceShuffle)

def UserUIMsgAddIsSeenCookieExchangeDialog(builder, isSeenCookieExchangeDialog):
    builder.PrependBoolSlot(82, isSeenCookieExchangeDialog, 0)

def AddIsSeenCookieExchangeDialog(builder, isSeenCookieExchangeDialog):
    UserUIMsgAddIsSeenCookieExchangeDialog(builder, isSeenCookieExchangeDialog)

def UserUIMsgAddIsSeenMySetHelp(builder, isSeenMySetHelp):
    builder.PrependBoolSlot(83, isSeenMySetHelp, 0)

def AddIsSeenMySetHelp(builder, isSeenMySetHelp):
    UserUIMsgAddIsSeenMySetHelp(builder, isSeenMySetHelp)

def UserUIMsgAddExchangeResourceResetTime(builder, exchangeResourceResetTime):
    builder.PrependInt64Slot(84, exchangeResourceResetTime, 0)

def AddExchangeResourceResetTime(builder, exchangeResourceResetTime):
    UserUIMsgAddExchangeResourceResetTime(builder, exchangeResourceResetTime)

def UserUIMsgAddExchangeResourceCountList(builder, exchangeResourceCountList):
    builder.PrependUOffsetTRelativeSlot(85, flatbuffers.number_types.UOffsetTFlags.py_type(exchangeResourceCountList), 0)

def AddExchangeResourceCountList(builder, exchangeResourceCountList):
    UserUIMsgAddExchangeResourceCountList(builder, exchangeResourceCountList)

def UserUIMsgStartExchangeResourceCountListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartExchangeResourceCountListVector(builder, numElems):
    return UserUIMsgStartExchangeResourceCountListVector(builder, numElems)

def UserUIMsgAddIsSeenMyDesignHelp(builder, isSeenMyDesignHelp):
    builder.PrependBoolSlot(86, isSeenMyDesignHelp, 0)

def AddIsSeenMyDesignHelp(builder, isSeenMyDesignHelp):
    UserUIMsgAddIsSeenMyDesignHelp(builder, isSeenMyDesignHelp)

def UserUIMsgAddIsHandoverFromOnToOff(builder, isHandoverFromOnToOff):
    builder.PrependBoolSlot(87, isHandoverFromOnToOff, 0)

def AddIsHandoverFromOnToOff(builder, isHandoverFromOnToOff):
    UserUIMsgAddIsHandoverFromOnToOff(builder, isHandoverFromOnToOff)

def UserUIMsgAddIsSeenReafstoneExchangeMonth(builder, isSeenReafstoneExchangeMonth):
    builder.PrependBoolSlot(88, isSeenReafstoneExchangeMonth, 0)

def AddIsSeenReafstoneExchangeMonth(builder, isSeenReafstoneExchangeMonth):
    UserUIMsgAddIsSeenReafstoneExchangeMonth(builder, isSeenReafstoneExchangeMonth)

def UserUIMsgAddIsSeenCatalogCompleteDialog(builder, isSeenCatalogCompleteDialog):
    builder.PrependBoolSlot(89, isSeenCatalogCompleteDialog, 0)

def AddIsSeenCatalogCompleteDialog(builder, isSeenCatalogCompleteDialog):
    UserUIMsgAddIsSeenCatalogCompleteDialog(builder, isSeenCatalogCompleteDialog)

def UserUIMsgAddIsNeedNewCatalogCompleteDialog(builder, isNeedNewCatalogCompleteDialog):
    builder.PrependBoolSlot(90, isNeedNewCatalogCompleteDialog, 0)

def AddIsNeedNewCatalogCompleteDialog(builder, isNeedNewCatalogCompleteDialog):
    UserUIMsgAddIsNeedNewCatalogCompleteDialog(builder, isNeedNewCatalogCompleteDialog)

def UserUIMsgAddIsNeedNewCookieExchangeDialog(builder, isNeedNewCookieExchangeDialog):
    builder.PrependBoolSlot(91, isNeedNewCookieExchangeDialog, 0)

def AddIsNeedNewCookieExchangeDialog(builder, isNeedNewCookieExchangeDialog):
    UserUIMsgAddIsNeedNewCookieExchangeDialog(builder, isNeedNewCookieExchangeDialog)

def UserUIMsgEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserUIMsgEnd(builder)
