# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserGulliverShipOpenDestinationOneSlotSetElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserGulliverShipOpenDestinationOneSlotSetElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserGulliverShipOpenDestinationOneSlotSetElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserGulliverShipOpenDestinationOneSlotSetElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserGulliverShipOpenDestinationOneSlotSetElement
    def DestinationId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def UserGulliverShipOpenDestinationOneSlotSetElementStart(builder):
    builder.StartObject(1)

def Start(builder):
    UserGulliverShipOpenDestinationOneSlotSetElementStart(builder)

def UserGulliverShipOpenDestinationOneSlotSetElementAddDestinationId(builder, destinationId):
    builder.PrependUint32Slot(0, destinationId, 0)

def AddDestinationId(builder, destinationId):
    UserGulliverShipOpenDestinationOneSlotSetElementAddDestinationId(builder, destinationId)

def UserGulliverShipOpenDestinationOneSlotSetElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserGulliverShipOpenDestinationOneSlotSetElementEnd(builder)
