# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserDealerSeenMasterSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserDealerSeenMasterSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserDealerSeenMasterSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserDealerSeenMasterSlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserDealerSeenMasterSlot
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserDealerSeenMasterSlot
    def MasterId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def UserDealerSeenMasterSlotStart(builder):
    builder.StartObject(2)

def Start(builder):
    UserDealerSeenMasterSlotStart(builder)

def UserDealerSeenMasterSlotAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserDealerSeenMasterSlotAddId(builder, id)

def UserDealerSeenMasterSlotAddMasterId(builder, masterId):
    builder.PrependUint32Slot(1, masterId, 0)

def AddMasterId(builder, masterId):
    UserDealerSeenMasterSlotAddMasterId(builder, masterId)

def UserDealerSeenMasterSlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserDealerSeenMasterSlotEnd(builder)
