# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserItemStockOneSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserItemStockOneSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserItemStockOneSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserItemStockOneSlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserItemStockOneSlot
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserItemStockOneSlot
    def ItemId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserItemStockOneSlot
    def Date(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserItemStockOneSlot
    def IsChecked(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserItemStockOneSlot
    def Num(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # UserItemStockOneSlot
    def Guid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserItemStockOneSlot
    def PutPlace(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # UserItemStockOneSlot
    def IsLock(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def UserItemStockOneSlotStart(builder):
    builder.StartObject(8)

def Start(builder):
    UserItemStockOneSlotStart(builder)

def UserItemStockOneSlotAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserItemStockOneSlotAddId(builder, id)

def UserItemStockOneSlotAddItemId(builder, itemId):
    builder.PrependUint32Slot(1, itemId, 0)

def AddItemId(builder, itemId):
    UserItemStockOneSlotAddItemId(builder, itemId)

def UserItemStockOneSlotAddDate(builder, date):
    builder.PrependUint32Slot(2, date, 0)

def AddDate(builder, date):
    UserItemStockOneSlotAddDate(builder, date)

def UserItemStockOneSlotAddIsChecked(builder, isChecked):
    builder.PrependBoolSlot(3, isChecked, 0)

def AddIsChecked(builder, isChecked):
    UserItemStockOneSlotAddIsChecked(builder, isChecked)

def UserItemStockOneSlotAddNum(builder, num):
    builder.PrependInt16Slot(4, num, 0)

def AddNum(builder, num):
    UserItemStockOneSlotAddNum(builder, num)

def UserItemStockOneSlotAddGuid(builder, guid):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(guid), 0)

def AddGuid(builder, guid):
    UserItemStockOneSlotAddGuid(builder, guid)

def UserItemStockOneSlotAddPutPlace(builder, putPlace):
    builder.PrependUint8Slot(6, putPlace, 0)

def AddPutPlace(builder, putPlace):
    UserItemStockOneSlotAddPutPlace(builder, putPlace)

def UserItemStockOneSlotAddIsLock(builder, isLock):
    builder.PrependBoolSlot(7, isLock, 0)

def AddIsLock(builder, isLock):
    UserItemStockOneSlotAddIsLock(builder, isLock)

def UserItemStockOneSlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserItemStockOneSlotEnd(builder)
