# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserItemFlowerbedGenePairNum(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserItemFlowerbedGenePairNum()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserItemFlowerbedGenePairNum(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserItemFlowerbedGenePairNum
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserItemFlowerbedGenePairNum
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserItemFlowerbedGenePairNum
    def Gene1Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserItemFlowerbedGenePairNum
    def Gene2Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserItemFlowerbedGenePairNum
    def Num(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def UserItemFlowerbedGenePairNumStart(builder):
    builder.StartObject(4)

def Start(builder):
    UserItemFlowerbedGenePairNumStart(builder)

def UserItemFlowerbedGenePairNumAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserItemFlowerbedGenePairNumAddId(builder, id)

def UserItemFlowerbedGenePairNumAddGene1Key(builder, gene1Key):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(gene1Key), 0)

def AddGene1Key(builder, gene1Key):
    UserItemFlowerbedGenePairNumAddGene1Key(builder, gene1Key)

def UserItemFlowerbedGenePairNumAddGene2Key(builder, gene2Key):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(gene2Key), 0)

def AddGene2Key(builder, gene2Key):
    UserItemFlowerbedGenePairNumAddGene2Key(builder, gene2Key)

def UserItemFlowerbedGenePairNumAddNum(builder, num):
    builder.PrependInt32Slot(3, num, 0)

def AddNum(builder, num):
    UserItemFlowerbedGenePairNumAddNum(builder, num)

def UserItemFlowerbedGenePairNumEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserItemFlowerbedGenePairNumEnd(builder)
