# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserSksAchievementOneSlotSetElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserSksAchievementOneSlotSetElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserSksAchievementOneSlotSetElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserSksAchievementOneSlotSetElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserSksAchievementOneSlotSetElement
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserSksAchievementOneSlotSetElement
    def KeyName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserSksAchievementOneSlotSetElement
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # UserSksAchievementOneSlotSetElement
    def UpdatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserSksAchievementOneSlotSetElement
    def KeyId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def UserSksAchievementOneSlotSetElementStart(builder):
    builder.StartObject(5)

def Start(builder):
    UserSksAchievementOneSlotSetElementStart(builder)

def UserSksAchievementOneSlotSetElementAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserSksAchievementOneSlotSetElementAddId(builder, id)

def UserSksAchievementOneSlotSetElementAddKeyName(builder, keyName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(keyName), 0)

def AddKeyName(builder, keyName):
    UserSksAchievementOneSlotSetElementAddKeyName(builder, keyName)

def UserSksAchievementOneSlotSetElementAddStatus(builder, status):
    builder.PrependUint8Slot(2, status, 0)

def AddStatus(builder, status):
    UserSksAchievementOneSlotSetElementAddStatus(builder, status)

def UserSksAchievementOneSlotSetElementAddUpdatedAt(builder, updatedAt):
    builder.PrependInt64Slot(3, updatedAt, 0)

def AddUpdatedAt(builder, updatedAt):
    UserSksAchievementOneSlotSetElementAddUpdatedAt(builder, updatedAt)

def UserSksAchievementOneSlotSetElementAddKeyId(builder, keyId):
    builder.PrependUint32Slot(4, keyId, 0)

def AddKeyId(builder, keyId):
    UserSksAchievementOneSlotSetElementAddKeyId(builder, keyId)

def UserSksAchievementOneSlotSetElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserSksAchievementOneSlotSetElementEnd(builder)
