# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserActivityListedInfoSetElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserActivityListedInfoSetElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserActivityListedInfoSetElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserActivityListedInfoSetElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserActivityListedInfoSetElement
    def KeyName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserActivityListedInfoSetElement
    def OtherPlayerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserActivityListedInfoSetElement
    def CreateAtTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserActivityListedInfoSetElement
    def OtherPositionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserActivityListedInfoSetElement
    def OtherActionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserActivityListedInfoSetElement
    def NpcPositionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserActivityListedInfoSetElement
    def NpcActionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserActivityListedInfoSetElement
    def Guid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def UserActivityListedInfoSetElementStart(builder):
    builder.StartObject(8)

def Start(builder):
    UserActivityListedInfoSetElementStart(builder)

def UserActivityListedInfoSetElementAddKeyName(builder, keyName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(keyName), 0)

def AddKeyName(builder, keyName):
    UserActivityListedInfoSetElementAddKeyName(builder, keyName)

def UserActivityListedInfoSetElementAddOtherPlayerId(builder, otherPlayerId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(otherPlayerId), 0)

def AddOtherPlayerId(builder, otherPlayerId):
    UserActivityListedInfoSetElementAddOtherPlayerId(builder, otherPlayerId)

def UserActivityListedInfoSetElementAddCreateAtTime(builder, createAtTime):
    builder.PrependInt64Slot(2, createAtTime, 0)

def AddCreateAtTime(builder, createAtTime):
    UserActivityListedInfoSetElementAddCreateAtTime(builder, createAtTime)

def UserActivityListedInfoSetElementAddOtherPositionId(builder, otherPositionId):
    builder.PrependInt32Slot(3, otherPositionId, 0)

def AddOtherPositionId(builder, otherPositionId):
    UserActivityListedInfoSetElementAddOtherPositionId(builder, otherPositionId)

def UserActivityListedInfoSetElementAddOtherActionId(builder, otherActionId):
    builder.PrependInt32Slot(4, otherActionId, 0)

def AddOtherActionId(builder, otherActionId):
    UserActivityListedInfoSetElementAddOtherActionId(builder, otherActionId)

def UserActivityListedInfoSetElementAddNpcPositionId(builder, npcPositionId):
    builder.PrependInt32Slot(5, npcPositionId, 0)

def AddNpcPositionId(builder, npcPositionId):
    UserActivityListedInfoSetElementAddNpcPositionId(builder, npcPositionId)

def UserActivityListedInfoSetElementAddNpcActionId(builder, npcActionId):
    builder.PrependInt32Slot(6, npcActionId, 0)

def AddNpcActionId(builder, npcActionId):
    UserActivityListedInfoSetElementAddNpcActionId(builder, npcActionId)

def UserActivityListedInfoSetElementAddGuid(builder, guid):
    builder.PrependInt64Slot(7, guid, 0)

def AddGuid(builder, guid):
    UserActivityListedInfoSetElementAddGuid(builder, guid)

def UserActivityListedInfoSetElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserActivityListedInfoSetElementEnd(builder)
