# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserLostItemQuestItemOneSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserLostItemQuestItemOneSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserLostItemQuestItemOneSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserLostItemQuestItemOneSlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserLostItemQuestItemOneSlot
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserLostItemQuestItemOneSlot
    def ItemLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserLostItemQuestItemOneSlot
    def Num(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserLostItemQuestItemOneSlot
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserLostItemQuestItemOneSlot
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def UserLostItemQuestItemOneSlotStart(builder):
    builder.StartObject(5)

def Start(builder):
    UserLostItemQuestItemOneSlotStart(builder)

def UserLostItemQuestItemOneSlotAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserLostItemQuestItemOneSlotAddId(builder, id)

def UserLostItemQuestItemOneSlotAddItemLabel(builder, itemLabel):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(itemLabel), 0)

def AddItemLabel(builder, itemLabel):
    UserLostItemQuestItemOneSlotAddItemLabel(builder, itemLabel)

def UserLostItemQuestItemOneSlotAddNum(builder, num):
    builder.PrependInt32Slot(2, num, 0)

def AddNum(builder, num):
    UserLostItemQuestItemOneSlotAddNum(builder, num)

def UserLostItemQuestItemOneSlotAddKind(builder, kind):
    builder.PrependInt32Slot(3, kind, 0)

def AddKind(builder, kind):
    UserLostItemQuestItemOneSlotAddKind(builder, kind)

def UserLostItemQuestItemOneSlotAddIndex(builder, index):
    builder.PrependInt32Slot(4, index, 0)

def AddIndex(builder, index):
    UserLostItemQuestItemOneSlotAddIndex(builder, index)

def UserLostItemQuestItemOneSlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserLostItemQuestItemOneSlotEnd(builder)
