# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserCampTerrainCustomizeOneSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserCampTerrainCustomizeOneSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserCampTerrainCustomizeOneSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserCampTerrainCustomizeOneSlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserCampTerrainCustomizeOneSlot
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserCampTerrainCustomizeOneSlot
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserCampTerrainCustomizeOneSlot
    def NotifyNew(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserCampTerrainCustomizeOneSlot
    def Own(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def UserCampTerrainCustomizeOneSlotStart(builder):
    builder.StartObject(4)

def Start(builder):
    UserCampTerrainCustomizeOneSlotStart(builder)

def UserCampTerrainCustomizeOneSlotAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserCampTerrainCustomizeOneSlotAddId(builder, id)

def UserCampTerrainCustomizeOneSlotAddLabel(builder, label):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(label), 0)

def AddLabel(builder, label):
    UserCampTerrainCustomizeOneSlotAddLabel(builder, label)

def UserCampTerrainCustomizeOneSlotAddNotifyNew(builder, notifyNew):
    builder.PrependBoolSlot(2, notifyNew, 0)

def AddNotifyNew(builder, notifyNew):
    UserCampTerrainCustomizeOneSlotAddNotifyNew(builder, notifyNew)

def UserCampTerrainCustomizeOneSlotAddOwn(builder, own):
    builder.PrependBoolSlot(3, own, 0)

def AddOwn(builder, own):
    UserCampTerrainCustomizeOneSlotAddOwn(builder, own)

def UserCampTerrainCustomizeOneSlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserCampTerrainCustomizeOneSlotEnd(builder)
