# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserShopDataItemOneSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserShopDataItemOneSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserShopDataItemOneSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserShopDataItemOneSlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserShopDataItemOneSlot
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserShopDataItemOneSlot
    def ShopItemLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserShopDataItemOneSlot
    def ShopSale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def UserShopDataItemOneSlotStart(builder):
    builder.StartObject(3)

def Start(builder):
    UserShopDataItemOneSlotStart(builder)

def UserShopDataItemOneSlotAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserShopDataItemOneSlotAddId(builder, id)

def UserShopDataItemOneSlotAddShopItemLabel(builder, shopItemLabel):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(shopItemLabel), 0)

def AddShopItemLabel(builder, shopItemLabel):
    UserShopDataItemOneSlotAddShopItemLabel(builder, shopItemLabel)

def UserShopDataItemOneSlotAddShopSale(builder, shopSale):
    builder.PrependBoolSlot(2, shopSale, 0)

def AddShopSale(builder, shopSale):
    UserShopDataItemOneSlotAddShopSale(builder, shopSale)

def UserShopDataItemOneSlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserShopDataItemOneSlotEnd(builder)
