# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserMembershipSeenContent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserMembershipSeenContent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserMembershipSeenContent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserMembershipSeenContent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserMembershipSeenContent
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserMembershipSeenContent
    def MembershipMenuButtonId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def UserMembershipSeenContentStart(builder):
    builder.StartObject(2)

def Start(builder):
    UserMembershipSeenContentStart(builder)

def UserMembershipSeenContentAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserMembershipSeenContentAddId(builder, id)

def UserMembershipSeenContentAddMembershipMenuButtonId(builder, membershipMenuButtonId):
    builder.PrependUint32Slot(1, membershipMenuButtonId, 0)

def AddMembershipMenuButtonId(builder, membershipMenuButtonId):
    UserMembershipSeenContentAddMembershipMenuButtonId(builder, membershipMenuButtonId)

def UserMembershipSeenContentEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserMembershipSeenContentEnd(builder)
