# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserDiaryExteriorOneSlotSetElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserDiaryExteriorOneSlotSetElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserDiaryExteriorOneSlotSetElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserDiaryExteriorOneSlotSetElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserDiaryExteriorOneSlotSetElement
    def ExteriorId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserDiaryExteriorOneSlotSetElement
    def Have(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def UserDiaryExteriorOneSlotSetElementStart(builder):
    builder.StartObject(2)

def Start(builder):
    UserDiaryExteriorOneSlotSetElementStart(builder)

def UserDiaryExteriorOneSlotSetElementAddExteriorId(builder, exteriorId):
    builder.PrependUint32Slot(0, exteriorId, 0)

def AddExteriorId(builder, exteriorId):
    UserDiaryExteriorOneSlotSetElementAddExteriorId(builder, exteriorId)

def UserDiaryExteriorOneSlotSetElementAddHave(builder, have):
    builder.PrependBoolSlot(1, have, 0)

def AddHave(builder, have):
    UserDiaryExteriorOneSlotSetElementAddHave(builder, have)

def UserDiaryExteriorOneSlotSetElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserDiaryExteriorOneSlotSetElementEnd(builder)
