# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserAdventureMapProgress(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserAdventureMapProgress()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserAdventureMapProgress(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserAdventureMapProgress
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserAdventureMapProgress
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserAdventureMapProgress
    def ItemId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserAdventureMapProgress
    def IsInProgress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserAdventureMapProgress
    def PatternId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # UserAdventureMapProgress
    def CurrentSquare(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # UserAdventureMapProgress
    def NextDiceNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # UserAdventureMapProgress
    def RewardReceivedSquares(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # UserAdventureMapProgress
    def RewardReceivedSquaresAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # UserAdventureMapProgress
    def RewardReceivedSquaresLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserAdventureMapProgress
    def RewardReceivedSquaresIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # UserAdventureMapProgress
    def NextDiceTableIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserAdventureMapProgress
    def PatternTableIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UserAdventureMapProgress
    def AdvancedMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def UserAdventureMapProgressStart(builder):
    builder.StartObject(10)

def Start(builder):
    UserAdventureMapProgressStart(builder)

def UserAdventureMapProgressAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserAdventureMapProgressAddId(builder, id)

def UserAdventureMapProgressAddItemId(builder, itemId):
    builder.PrependUint32Slot(1, itemId, 0)

def AddItemId(builder, itemId):
    UserAdventureMapProgressAddItemId(builder, itemId)

def UserAdventureMapProgressAddIsInProgress(builder, isInProgress):
    builder.PrependBoolSlot(2, isInProgress, 0)

def AddIsInProgress(builder, isInProgress):
    UserAdventureMapProgressAddIsInProgress(builder, isInProgress)

def UserAdventureMapProgressAddPatternId(builder, patternId):
    builder.PrependUint8Slot(3, patternId, 0)

def AddPatternId(builder, patternId):
    UserAdventureMapProgressAddPatternId(builder, patternId)

def UserAdventureMapProgressAddCurrentSquare(builder, currentSquare):
    builder.PrependUint8Slot(4, currentSquare, 0)

def AddCurrentSquare(builder, currentSquare):
    UserAdventureMapProgressAddCurrentSquare(builder, currentSquare)

def UserAdventureMapProgressAddNextDiceNumber(builder, nextDiceNumber):
    builder.PrependUint8Slot(5, nextDiceNumber, 0)

def AddNextDiceNumber(builder, nextDiceNumber):
    UserAdventureMapProgressAddNextDiceNumber(builder, nextDiceNumber)

def UserAdventureMapProgressAddRewardReceivedSquares(builder, rewardReceivedSquares):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(rewardReceivedSquares), 0)

def AddRewardReceivedSquares(builder, rewardReceivedSquares):
    UserAdventureMapProgressAddRewardReceivedSquares(builder, rewardReceivedSquares)

def UserAdventureMapProgressStartRewardReceivedSquaresVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartRewardReceivedSquaresVector(builder, numElems):
    return UserAdventureMapProgressStartRewardReceivedSquaresVector(builder, numElems)

def UserAdventureMapProgressAddNextDiceTableIndex(builder, nextDiceTableIndex):
    builder.PrependInt32Slot(7, nextDiceTableIndex, 0)

def AddNextDiceTableIndex(builder, nextDiceTableIndex):
    UserAdventureMapProgressAddNextDiceTableIndex(builder, nextDiceTableIndex)

def UserAdventureMapProgressAddPatternTableIndex(builder, patternTableIndex):
    builder.PrependInt32Slot(8, patternTableIndex, 0)

def AddPatternTableIndex(builder, patternTableIndex):
    UserAdventureMapProgressAddPatternTableIndex(builder, patternTableIndex)

def UserAdventureMapProgressAddAdvancedMode(builder, advancedMode):
    builder.PrependUint8Slot(9, advancedMode, 0)

def AddAdvancedMode(builder, advancedMode):
    UserAdventureMapProgressAddAdvancedMode(builder, advancedMode)

def UserAdventureMapProgressEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserAdventureMapProgressEnd(builder)
