# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Acpcc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserActivityEventMatPainSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserActivityEventMatPainSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserActivityEventMatPainSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserActivityEventMatPainSlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserActivityEventMatPainSlot
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserActivityEventMatPainSlot
    def CampaignId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserActivityEventMatPainSlot
    def ItemId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UserActivityEventMatPainSlot
    def Point(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def UserActivityEventMatPainSlotStart(builder):
    builder.StartObject(4)

def Start(builder):
    UserActivityEventMatPainSlotStart(builder)

def UserActivityEventMatPainSlotAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    UserActivityEventMatPainSlotAddId(builder, id)

def UserActivityEventMatPainSlotAddCampaignId(builder, campaignId):
    builder.PrependUint32Slot(1, campaignId, 0)

def AddCampaignId(builder, campaignId):
    UserActivityEventMatPainSlotAddCampaignId(builder, campaignId)

def UserActivityEventMatPainSlotAddItemId(builder, itemId):
    builder.PrependUint32Slot(2, itemId, 0)

def AddItemId(builder, itemId):
    UserActivityEventMatPainSlotAddItemId(builder, itemId)

def UserActivityEventMatPainSlotAddPoint(builder, point):
    builder.PrependInt32Slot(3, point, 0)

def AddPoint(builder, point):
    UserActivityEventMatPainSlotAddPoint(builder, point)

def UserActivityEventMatPainSlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserActivityEventMatPainSlotEnd(builder)
